### ISSUE TITLE
Fix Product description on Landing page

### ISSUE THREAD

**Issue by RaghunandhanV** [rsj-rishabh/urbanClapClone#134]
**Describe the bug**
The Landing page has a section devoted to the application description. But the section doesn't have sensible text.

**To Reproduce**
1. Go to http://localhost:4200/home
2. Scroll down
3. See the section with product description with text 'Blandit varius ut praesent nascetur...' and 'Integer volutpat ante et accumsan...'

**Expected behavior**
A clear and concise description of various features of the app must be given here.

**Screenshots**
![text error](https://user-images.githubusercontent.com/95204169/164058346-207221a8-7ce3-43f2-a6e5-a51e48b41155.JPG)

**Comment by pkgprateek** [comment]
Closing #134

Completed
