### ISSUE TITLE
Dummy List API Error

### ISSUE THREAD

**Issue by pkgprateek** [rsj-rishabh/urbanClapClone#14]
**Describe the bug**
Mux API is not able to be initialized properly. Loading for the local host is not working. 

**To Reproduce**
1. Go to the root project folder.
2. run "go mod init server/app"
3. Goto server and run "go run app.go"
4. See the error. The server does not start.

**Expected behavior**
it was expected that the server would start at localhost:8000 but some CRUD functions may not work. But running the app does not start the server now.

**Expected Fix**
Either change the mux to inbuild HTTP functions or find a better HTTP package. The services are not able to initialized, which needs to be checked.

**Comment by rsj-rishabh** [comment]
Fetch branch `rishabh`
Go to servers
Run `go run main.go`

Should fix the issue.
