### ISSUE TITLE
Not able to see login and register after service list implementation

### ISSUE THREAD

**Issue by rsj-rishabh** [rsj-rishabh/urbanClapClone#25]
**Describe the bug**
The routes to login and register are not rendering the webpage.

**To Reproduce**
Run the current code in `dev` branch.
Click on `login` or `register`

**Expected behavior**
Webpages should be visible as attached.

**Screenshots**
<img width="1440" alt="Screen Shot 2022-02-04 at 3 07 38 PM" src="https://user-images.githubusercontent.com/32019969/152596802-0494012f-da24-4d2d-bc95-f1f2e0812ea5.png">

**Comment by Skillic-Kaiser** [comment]
Fixed issue via Commit #26
